from os import environ as env

DEBUG = True

SQLALCHEMY_TRACK_MODIFICATIONS = True

CSRF_ENABLED = True

SSL_REQUIRED = False
HOST = env.get('HOST', '0.0.0.0')
PORT = int(env.get('PORT', 8888))

DEBUG_TB_INTERCEPT_REDIRECTS = False

MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16M max upload size

# SQLALCHEMY_DATABASE_URI = env.get('DATABASE_URL', 'postgresql:///easypairings')
# SECRET_KEY = 'backend-dev'

# REDIS_URL = env.get('REDIS_URL', env.get('REDISTOGO_URL', 'redis://localhost:6379'))

# # mail server configuration
# DEFAULT_MAIL_SENDER = 'backend@yourdomain.com'

# # Flask-Security configuration
# SECURITY_PASSWORD_HASH = 'bcrypt'
# # generated by "How to generate good secret keys" here:
# # http://flask.pocoo.org/docs/quickstart/#admonition-how-to-generate-good-secret-keys
# SECURITY_PASSWORD_SALT = ':\xf8%\xc8\xe3\x89g0p\xf9\xc36\x9d\xe7+\x93\x8c\x94w\x0c\xcf\xc4\xa1\x1b'
# SECURITY_DEFAULT_REMEMBER_ME = True
# # FIXME: is this the right address?
# SECURITY_EMAIL_SENDER = DEFAULT_MAIL_SENDER
# # SECURITY_URL_PREFIX = '/account'
# SECURITY_UNAUTHORIZED_VIEW = '/'
# # SECURITY_POST_LOGIN_VIEW = '/account/login-redirect/'
# # SECURITY_POST_LOGOUT_VIEW = rebase_url('http://easypairings.com', base_url)
# SECURITY_RECOVERABLE = True
# SECURITY_TRACKABLE = True
# SECURITY_CHANGEABLE = True
# # REMEMBER_COOKIE_DOMAIN = rebase_url('.easypairings.com', base_url)
# SECURITY_RESET_PASSWORD_WITHIN = '30 days'
# SECURITY_CONFIRM_SALT = env.get('CONFIRM_SALT', '\xe6\xd5\x06\x96m\xcf\x8a\xa1=aq\xd6\xfd_/l\xcd\xc7\r\x15\xe5@aj')
# SECURITY_RESET_SALT = env.get('RESET_SALT', '-/\xa3\xce\xe3\xbfN\xc6\x99\x8d\xc1\x7fp\x02\xcb\xbbG\xf4\xbb\xfad\xcdG[')
# SECURITY_LOGIN_SALT = env.get('LOGIN_SALT', '\xdeBB\xa1\x113\x82\x083\x07\xec\xda\xb4\t#\xb2\xec\x0bMu\x8e\xfcr\xca')
# SECURITY_REMEMBER_SALT = env.get('REMEMBER_SALT', '\xe9\xdf\nb$\x92\x1cSn\xaft\x14q\xb3sq6[\x9a;\xd8\xfa\xd8\xcf')

SENTRY_DSN = env.get('SENTRY_DSN')
SENTRY_DSN_PUBLIC = env.get('SENTRY_DSN_PUBLIC')
